# Generated by Django 6.0.3 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomprenom", models.CharField(max_length=120)),
                ("service", models.CharField(max_length=80)),
                ("mail", models.EmailField(max_length=254, unique=True)),
                ("paye", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "utilisateur",
            },
        ),
    ]
