# Generated by Django 6.0.3 on 2026-04-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_update_historique_mensuel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historique",
            name="utilisateur",
            field=models.ForeignKey(
                db_column="id_utilisateur",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historiques",
                to="blog.utilisateur",
            ),
        ),
    ]
