# Generated by Django 6.0.3 on 2026-04-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_rename_utilisateur_column"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Historique",
        ),
        migrations.CreateModel(
            name="Historique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("heure", models.TimeField(auto_now_add=True)),
                ("heures_sup", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("prime", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("mois", models.PositiveSmallIntegerField()),
                ("annee", models.PositiveSmallIntegerField()),
                (
                    "utilisateur",
                    models.ForeignKey(
                        db_column="id_utilisateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques",
                        to="blog.utilisateur",
                    ),
                ),
            ],
            options={
                "db_table": "historique",
            },
        ),
        migrations.AddConstraint(
            model_name="historique",
            constraint=models.UniqueConstraint(
                fields=("utilisateur", "mois", "annee"),
                name="unique_historique_utilisateur_mois",
            ),
        ),
    ]
